website/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from flask_mysqldb import MySQLdb
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from datetime import date
from . import mysql


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # fetching info from the form
        acc_type = request.form.get('type')
        username = request.form.get('username')
        password = request.form.get('password')

        # fetching info from db
        cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cur.execute(
            """SELECT * FROM authorization WHERE username = %s AND account_type = %s""", (username, acc_type))
        result = cur.fetchone()
        # print(result)
        cur.close()
        # if the user exists
        if result is not None:
            user = User(result['account_id'], result['account_type'],
                        result['username'], result['email'], result['encrypted_password'])
            # checking password
            if check_password_hash(user.enc_password, password):
                login_user(user, remember=True)
                return redirect(url_for('views.profile'))
            else:
                # incorrect password
                flash('Incorrect Password', 'error')
                return render_template('login.html', user=current_user)
        else:
            # if the user does not exist, redirect to sign up page
            return redirect(url_for('auth.signup'))

    if request.method == 'GET':
        if current_user.is_authenticated:
            return redirect(url_for('views.profile'))
        else:
            return render_template('login.html', user=current_user)


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    # fetching info from the form
    if request.method == 'POST':
        acc_type = request.form.get('type')
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        username = request.form.get('username')
        email = request.form.get('email')
        password1 = request.form.get('set_pass')
        password2 = request.form.get('confirm_pass')

        # fetching info from db
        cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cur.execute(
            """SELECT username, email FROM authorization WHERE (username = %s OR email = %s) and account_type = %s""", (username, email, acc_type))
        result = cur.fetchall()
        print(result)
        cur.close()

        # checking if the username and email are unique
        if len(result) > 0:
            # flash
            flash('Username/Email already exists', 'error')
            return render_template('sign_up.html', user=current_user)
        # checking if valid names were inputted
        elif len(firstname) < 2 or len(lastname) < 2:
            # flash
            flash('Input a valid first name and last name', 'error')
            return render_template('sign_up.html', user=current_user)
        # checking length of the password
        elif len(password1) < 8:
            # flash
            flash('Password too small. Minimum Length is 8.', 'error')
            return render_template('sign_up.html', user=current_user)
        # checking if the two passwords match
        elif password1 != password2:
            flash("Passwords don't match", 'error')
            return render_template('sign_up.html', user=current_user)

        else:
            # add user to the data base
            enc_password = generate_password_hash(password1)
            cur = mysql.connection.cursor()
            cur.execute("""INSERT INTO authorization (account_type, username, email, encrypted_password) VALUES(%s, %s, %s, %s)""",
                        (acc_type, username, email, enc_password))
            mysql.connection.commit()

            cur.execute(
                """SELECT account_id FROM authorization WHERE username = %s AND account_type = %s ORDER BY account_id DESC""", (username, acc_type))
            account_id = cur.fetchone()[0]

            if acc_type == 'student':
                cur.execute("""INSERT INTO student (firstname, lastname, join_date, account_id) VALUES (%s, %s, %s, %s)""",
                            (firstname, lastname, date.today(), account_id))
            else:
                cur.execute("""INSERT INTO teacher (firstname, lastname, join_date, account_id) VALUES (%s, %s, %s, %s)""",
                            (firstname, lastname, date.today(), account_id))

            mysql.connection.commit()
            user = User(
                account_id, 'student', email, username, enc_password)
            login_user(user, remember=True)
            return redirect(url_for('views.profile'))

    if request.method == 'GET':
        if current_user.is_authenticated:
            return redirect(url_for('views.profile'))
        else:
            return render_template('sign_up.html', user=current_user)


@auth.route('/update_account', methods=['POST'])
@login_required
def update_account():
    old_pass = request.form.get('old_password')
    new_pass = request.form.get('new_password')
    confirm_pass = request.form.get('confirm_password')
    # print(type(new_pass))

    if check_password_hash(current_user.enc_password, old_pass):
        cur = mysql.connection.cursor()
        if new_pass == confirm_pass:
            if len(new_pass) < 8:
                flash('Password is too small. Minimum Length is 8.', 'error')
                return redirect(url_for('views.account'))
            cur.execute("""UPDATE authorization SET encrypted_password = %s WHERE account_id = %s""",
                        (generate_password_hash(new_pass), current_user.account_id))
            mysql.connection.commit()
            current_user.enc_password = generate_password_hash(new_pass)
        else:
            flash("Passwords don't match", 'error')

        return redirect(url_for('views.account'))
    else:
        flash('Incorrect Password', 'error')
        return redirect(url_for('views.account'))


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

website/templates/account.html
{% extends 'base.html'%}

{% block title %}Account Settpassword{% endblock%}

{% block content %}
<div class="account_body">
    <div class="account_container">
        <div class="account_title">Account Settings</div>
        <div class="account_content">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert">
                <span class="alertclosebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            {% endwith %}
            <form action="{{ url_for('auth.update_account') }}" method="POST">
                <div class="account_user-details">
                    <div class="account_input-box">
                        <span class="account_details">First Name</span>
                        <input type="text" name="firstname" placeholder="Last name" value="{{ firstname }}" disabled>
                    </div>
                    <div class="account_input-box">
                        <span class="account_details">Last Name</span>
                        <input type="text" name="lastname" placeholder="Last Name" value="{{ lastname }}" disabled>
                    </div>
                    <div class="account_input-box">
                        <span class="account_details">Username</span>
                        <input type="text" name="username" placeholder="Username" value="{{ user.username }}" disabled>
                    </div>
                    <div class="account_input-box">
                        <span class="account_details">Email</span>
                        <input type="text" name="email" placeholder="Email" value="{{ user.email }}" disabled>
                    </div>
                    <div class="account_input-box">
                        <span class="account_details">Old Password</span>
                        <input type="password" name="old_password" placeholder="Old Password" required>
                    </div>
                    <div class="account_input-box">
                        <span class="account_details">New Password</span>
                        <input type="password" name="new_password" placeholder="New Password" required>
                    </div>
                    <div class="account_input-box">
                        <span class="account_details">Confirm Password</span>
                        <input type="password" name="confirm_password" placeholder="Confirm New password" required>
                    </div>
                </div>

                <div class="account_button">
                    <input type="submit" value="Submit">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock%}

website/templates/assessment.html
{% extends 'base.html'%}

{% block title %}{{ assessment.assessment_title }}{% endblock%}

{% block content %}

<form method="POST">
    <div class="assessment_body">
        {% for question in questions %}

        <div class="assessment_quize">
            <div class="assessment_question-bar">
                <h2 class="assessment_qestion"><label for="options{{ loop.index }}">{{ question.text }}</label></h2>
                <ul>
                    <li>
                        <input type="radio" name="options{{ loop.index }}" value="1" id="a{{ loop.index }}"
                            class="assessment_ansList">
                        <label for="a{{ loop.index }}" class="assessment_ansa">{{ question.option1 }}</label>
                    </li>
                    <li>
                        <input type="radio" name="options{{ loop.index }}" value="2" id="b{{ loop.index }}"
                            class="ansList">
                        <label for="b{{ loop.index }}" class="assessment_ansb">{{ question.option2 }}</label>
                    </li>
                    <li>
                        <input type="radio" name="options{{ loop.index }}" value="3" id="c{{ loop.index }}"
                            class="ansList">
                        <label for="c{{ loop.index }}" class="assessment_ansc">{{ question.option3 }}</label>
                    </li>
                    <li>
                        <input type="radio" name="options{{ loop.index }}" value="4" id="d{{ loop.index }}"
                            class="ansList">
                        <label for="d{{ loop.index }}" class="assessment_ansd">{{ question.option4 }}</label>
                    </li>

                </ul>

            </div>
        </div>

        {% endfor %}
        <div class="assessment_footer-button">
            {% if user.account_type == 'teacher' %}
            <button type="submit" id="submit" class="assessment_submitBtn" disabled>Submit</button>
            {% else %}
            <button type="submit" id="submit" class="assessment_submitBtn">Submit</button>
            {% endif %}
        </div>
    </div>

</form>

{% endblock%}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</head>

<body>
    <div class="wrapper">
        <nav>
            <input type="checkbox" id="show-search">
            <input type="checkbox" id="show-menu">
            <label for="show-menu" class="menu-icon"><i class="fas fa-bars"></i></label>
            <div class="content">
                <div class="logo"><a href="/"><i class="fas fa-graduation-cap"></i></a></div>
                <div class="logo"><a href="/">E-Learning</a></div>

                <ul class="links">
                    <li><a href="/">Home</a></li>
                    <li>
                        <a href="#" class="desktop-link">Categories</a>
                        <input type="checkbox" id="show-features">
                        <label for="show-features">Categories</label>
                        <ul>
                            <li><a href="/category/Web-Development">Web Development</a></li>
                            <li><a href="/category/Software-Development">Software Development</a></li>
                            <li><a href="/category/Machine-Learning">Machine Learning</a></li>
                            <li><a href="/category/Deep-Learning">Deep Learning</a></li>
                        </ul>
                    </li>
                    <!-- <li><a href="#">Contact Us</a></li> -->
                    {% if user.is_authenticated %}
                    <li>
                        <a href="#" class="desktop-link">Profile</a>
                        <input type="checkbox" id="show-features">
                        <label for="show-features">Profile</label>
                        <ul>
                            <li><a href="/profile">Profile</a></li>
                            <li><a href="/account">Account</a></li>
                            <li><a href="/logout">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="/login">Login</a></li>
                    <li><a href="/signup">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
            <label for="show-search" class="search-icon"><i class="fas fa-search"></i></label>
            <form action="/search" method="POST" class="search-box">
                <input name="search_term" type="text" placeholder="Type Something to Search..." required>
                <button type="submit" class="go-icon"><i class="fas fa-long-arrow-alt-right"></i></button>
            </form>
        </nav>
    </div>
    
    <div class="page_content">{% block content %}{% endblock %}</div>

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="footer-col">
                    <h4>company</h4>
                    <ul>
                        <li><a href="#">about us</a></li>
                        <li><a href="#">privacy policy</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>get help</h4>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Browse Categories</h4>
                    <ul>
                        <li><a href="/category/Web-Development">Web Development</a></li>
                        <li><a href="/category/Software-Development">Software Development</a></li>
                        <li><a href="/category/Machine-Learning">Machine Learning</a></li>
                        <li><a href="/category/Deep-Learning">Deep Learning</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>follow us</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</body>

</html

website/templates/browse.html
{% extends 'base.html'%}

{% block title %}{{ title }}{% endblock%}

{% block content %}
<div class="browse_body">
    <h1 style="font-size: 50px; font-family:monospace;">
        Search Results
    </h1>
{% for course in courses %}
    <div class="browse_courses-container">
        <div class="browse_course">
            <div class="browse_course-preview">
                <h6>Course</h6>
                <h2>{{ course.course_title}}</h2>
            </div>
            <div class="browse_course-info">
                <h6>Instructor: {{ course.teacher }}</h6>
                <h2>Category:</h2> 
                <h2>{{ course.category }}</h2>
                <button class="browse_btn" id="view-course-button{{ course.course_id }}">View Course</button>
                <script>
                    document.getElementById('view-course-button{{ course.course_id }}').onclick = function() {
                        location.href = "{{ url_for('views.course', course_id=course.course_id) }}"
                    }
                </script>
            </div>
        </div>
    </div>
{% endfor %}
</div>

{% endblock%}

website/templates/content.html
{% extends 'base.html'%}

{% block title %}{{ study_material.content_title }}{% endblock%}

{% block content %}
<div class="content_space">
    <div class="content_container">
        <div class="content_titles">
            <h1>{{ study_material.content_title }}</h1>
        </div>
    </div>
    
    <center>
        <iframe src="{{ study_material.link }}" frameborder="10" width="100%" height="600px"></iframe>
    </center>

</div>

<div class="comments_space">
    <div class="content_titles"><h2>Comments</h2></div>
    {% for comment in comments %}
    <div class="early_comment_wrapper">
        <div class="early_comments">
            <h2>{{ comment.posted_by }} ({{ comment.posted_account }})</h2> 
            <div class="time">{{ comment.post_time }}</div>
            <!-- <br> -->
            <p>{{ comment.text }}</p>
        </div>
    </div>
    {% endfor %}
    <form method="POST">
        <div class="content_textarea_wrapper">
            <input type="text" name="comment" placeholder="Please comment here" autocomplete="off" required>
            <button type="submit" class="comment_button">Comment</button>
        </div>
    </form>
</div>
{% endblock%}

website/templates/course.html
{% extends 'base.html'%}

{% block title %}{{ course.course_title }}{% endblock%}

{% block content %}
<div class="course_content">
    <section class="course_top">
        <div class="course_top_title">
            <h1>{{ course.course_title}}</h1>
        </div>
        <div class="course_top_title">
            <h3>Category: {{ course.category }}</h3>
        </div>

    </section>
    <div class="course_description">
        <h3>Descriptioin:</h3>
        <span>{{ course.description }}</span><br>
        {% if rating_count != 0 %}
        <span>Rating: {{ rating }} (by {{ rating_count }} students) </span>
        {% else %}
        <span>Rating: Not rated yet </span>
        {% endif %}
    </div>




    {% if user.account_type == 'student' and not enrolled %}
    <div class="course_button_container">
        <button class="open-button" type="button" id="enroll_button">Enroll</button>
        <script>
            document.getElementById("enroll_button").onclick = function () {
                location.href = "{{ url_for('views.enroll', course_id = course.course_id) }}"
            };
        </script>
    </div>
    {% endif %}

    {% if user.account_type == 'student' and enrolled and not rated %}
    <div class="course_button_container">
        <button class="open-button" type="button" id="feedback_button">Feedback</button>
        <script>
            document.getElementById("feedback_button").onclick = function () {
                location.href = "{{ url_for('views.feedback', course_id=course.course_id) }}";
            };
        </script>
    </div>
    {% endif %}

    {% if user.account_type == 'teacher' and creator %}
    <div class="course_button_container">
        <button class="open-button" onclick="openForm('addContent')">Add Content</button>
    </div>

    <div class="add_content_container">
        <div class="form-popup" id="addContent">
            <form action="{{ url_for('views.add_content', course_id=course.course_id) }}" method="POST">
                <h1>Add Content</h1>
                <label for="content_title"></label>
                <input type="text" class="course_title" placeholder="Content Title" name="content_title" autocomplete="off" required><br>
    
                <label for="link"></label>
                <input type="url" class="course_url" placeholder="Link" name="link" autocomplete="off" required><br>
    
                <button type="submit" class="course_submit">Add</button>
                <button type="button" class="course_close" onclick="closeForm('addContent')">Close</button>
            </form>
        </div>
    </div>

    <div class="course_button_container">
        <button class="open-button" onclick="openForm('addAssessment')">Add Assessment</button>
    </div>
    
    <div class="add_content_container">
        <div class="form-popup" id="addAssessment">
            <form action="{{ url_for('views.add_assessment', course_id=course.course_id) }}" method="POST">
                <h2>Add Assessment</h2>
                <label for="assessment_title"></label>
                <input type="text" class="course_title" id="assessment_title_input" name="assessment_title"
                    placeholder="Assessment Title" autocomplete="off" required>
                <button class="course_submit" type="submit" id="add_assessment_submit">Add</button>
                <button type="button" class="course_close" onclick="closeForm('addAssessment')">Close</button>
            </form>
        </div>
    </div>
    {% endif %}

    
    <div class="course_outter_div">
        <div class="course_heading">
            <h1>Contents</h1>
        </div>
        {% for study_material in study_materials %}
        <!-- show the study materials  -->
        <div class="display_container">
            <div class="course_display" id="contentBox{{ loop.index }}">
                <div class="course_display_iner">
                    <h4>{{ study_material.content_title }}</h4>
                </div>
            </div>
            <script>
                document.getElementById('contentBox{{ loop.index }}').onclick = function () {
                    location.href = "{{ url_for('views.content', course_id=course.course_id, content_id=study_material.content_id) }}"
                }
            </script>
        </div>
        {% endfor %}
    </div>

    

    
    <div class="course_outter_div">
        <div class="course_heading">
            <h1>Assessments</h1>
        </div>
        {% for assessment in assessments %}
        <!-- show the study materials  -->
        <div class="display_container">
            <div class="course_display" id="assessmentBox{{ loop.index }}">
                <div class="course_display_iner">
                    <h4>{{ assessment.assessment_title }}</h4>
                </div>
            </div>
            <script>
                document.getElementById('assessmentBox{{ loop.index }}').onclick = function () {
                    location.href = "{{ url_for('views.assessment', course_id=course.course_id, assessment_id=assessment.assessment_id) }}"
                }
            </script>
        </div>
        {% endfor %}
    </div>

    
</div>

{% endblock%}

website/templates/feedback.html
{% extends 'base.html'%}

{% block title %}Feedback{% endblock%}

{% block content %}
<div class="feedback_body">
    <div class="feedback_container">
        <center>
            <h1>Feedback</h1>
        </center>
        <!-- <div class="feedback_post">
            <div class="feedback_text">Thanks for rating us!</div>
            <div class="feedback_edit">EDIT</div>
        </div> -->
        <div class="feedback_star-widget">
            <form action="#" method="POST">
                <input type="radio" name="rate" value="5"  id="rate-5">
                <label for="rate-5" class="fas fa-star"></label>
                <input type="radio" name="rate" value="4" id="rate-4">
                <label for="rate-4" class="fas fa-star"></label>
                <input type="radio" name="rate" value="3" id="rate-3">
                <label for="rate-3" class="fas fa-star"></label>
                <input type="radio" name="rate" value="2" id="rate-2">
                <label for="rate-2" class="fas fa-star"></label>
                <input type="radio" name="rate" value="1" id="rate-1">
                <label for="rate-1" class="fas fa-star"></label>
                <header></header>
                <div class="feedback_textarea">
                    <input type="text" name="review" placeholder="Describe your experience.." autocomplete="off">
                </div>
                <div class="feedback_btn">
                    <button type="submit">Post</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock%}

website/templates/home.html
{% extends 'base.html'%}

{% block title %}Home{% endblock%}

{% block content %}
<section class="home" id="home">
    <section class="home" id="home">

        <div class="body_content">
            <h1>learn online from home</h1>
            <p>
                No need to go out to learn. <br>
                No more paying for Education. <br>
                Join us now and learn for free from the comfort of your home.
            </p>
            <button id="join_us">Join Us</button>
            <script>
                document.getElementById("join_us").onclick = function () {
                    location.href = "{{ url_for('auth.signup') }}"
                }
            </script>
        </div>
    </section>

    <section class="about" id="about">
        <h1 class="heading">About Us</h1>
        <h3 class="title">Join us on our jouney</h3>

        <div class="row">
            <div class="image">
                <img src="{{ url_for('static', filename='home_pic.jpg') }}">
            </div>
            <div class="body_content">
                <h3>Learn and Teach From Anywhere For Free</h3>
                <p>E-Learning is a platform where you can learn and teach from your home. 
                    We offer you the platform to join as a teacher and make your own courses. We give you the opportunity to learn for free. 
                    Thousands of courses made by qualified teachers at your door step. Don't waste a second and join us right now.
                </p>
                <button id="start_now">Start Now</button>
                <script>
                    document.getElementById("start_now").onclick = function() {
                        location.href = "{{ url_for('auth.signup') }}"
                    }
                </script>
            </div>
        </div>

    </section>


    <!-- about section ends -->

    <!-- teacher section starts  -->

    <!-- <section id="teacher" class="teacher">

        <h1 class="heading">Our Top Teachers</h1>
        <h3 class="title">meet professional trainers</h3>

        <div class="card-container">

            <div class="card">
                <img src="teacher_1.jpg" alt="">
                <h3>Ahmed Symum Swapno</h3>
                <p>i love Coding</p>
                <div class="icons">
                    <a href="#" class="fab fa-facebook-f"></a>
                    <a href="#" class="fab fa-twitter"></a>
                    <a href="#" class="fab fa-instagram"></a>
                    <a href="#" class="fab fa-github"></a>
                </div>
            </div>

            <div class="card">
                <img src="teacher_2.jpg" alt="">
                <h3>Swapnil Ghosh</h3>
                <p>i love teaching</p>
                <div class="icons">
                    <a href="#" class="fab fa-facebook-f"></a>
                    <a href="#" class="fab fa-twitter"></a>
                    <a href="#" class="fab fa-instagram"></a>
                    <a href="#" class="fab fa-github"></a>
                </div>
            </div>

            <div class="card">
                <img src="teacher_3.jpg" alt="">
                <h3>Mahmudul Hamim</h3>
                <p>i love teaching</p>
                <div class="icons">
                    <a href="#" class="fab fa-facebook-f"></a>
                    <a href="#" class="fab fa-twitter"></a>
                    <a href="#" class="fab fa-instagram"></a>
                    <a href="#" class="fab fa-github"></a>
                </div>
            </div>

        </div>


    </section>

    <!-- teacher section ends -->

    <!-- course section starts  -->

    <!-- <section id="course" class="course">

        <h1 class="heading">our courses</h1>
        <h3 class="title">upgrade your skills with newest courses</h3>


        <div class="box-container">

            <div class="box">
                <i class="fab fa-html5"></i>
                <h3>html5</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, ex.</p>
            </div>

            <div class="box">
                <i class="fab fa-css3-alt"></i>
                <h3>css3</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, ex.</p>
            </div>

            <div class="box">
                <i class="fab fa-js-square"></i>
                <h3>javascript</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, ex.</p>
            </div>

            <div class="box">
                <i class="fas fa-code"></i>
                <h3>web development</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, ex.</p>
            </div>

            <div class="box">
                <i class="fas fa-bullhorn"></i>
                <h3>seo marketing</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, ex.</p>
            </div>

            <div class="box">
                <i class="fas fa-paint-brush"></i>
                <h3>graphic design</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, ex.</p>
            </div>

        </div>

    </section> -->

    <!-- course section ends -->
{% endblock%}

website/templates/result.html
{% extends 'base.html'%}

{% block title %}Result{% endblock%}

{% block content %}
<div class="result_body">
    <div class="card-wrap">
        <div class="card-header one">
            <i class="fas fa-code"></i>
        </div>
        <div class="card-content">
            <h1 class="card-title">{{ marks }}</h1>
            <p class="card-text">Thanks For Participating the assessment. Hope you have a great day</p>
        </div>
    </div>
</div>

{% endblock%}